USE [master]
GO
/****** Object:  Database [AtonDB]    Script Date: 31.05.2024 4:23:41 ******/
CREATE DATABASE [AtonDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AtonDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\AtonDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AtonDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\AtonDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AtonDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AtonDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AtonDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AtonDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AtonDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AtonDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AtonDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [AtonDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AtonDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AtonDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AtonDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AtonDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AtonDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AtonDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AtonDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AtonDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AtonDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AtonDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AtonDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AtonDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AtonDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AtonDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AtonDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AtonDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AtonDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AtonDB] SET  MULTI_USER 
GO
ALTER DATABASE [AtonDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AtonDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AtonDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AtonDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AtonDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AtonDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AtonDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [AtonDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AtonDB]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 31.05.2024 4:23:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Guid] [uniqueidentifier] NOT NULL,
	[Login] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Gender] [int] NOT NULL,
	[Birthday] [datetime] NULL,
	[Admin] [bit] NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[CreatedBy] [nvarchar](50) NOT NULL,
	[ModifiedOn] [datetime] NULL,
	[ModifiedBy] [nvarchar](50) NULL,
	[RevokedOn] [datetime] NULL,
	[RevokedBy] [nvarchar](50) NULL,
 CONSTRAINT [PK__Users__A2B5777CF43803CA] PRIMARY KEY CLUSTERED 
(
	[Guid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Users] ([Guid], [Login], [Password], [Name], [Gender], [Birthday], [Admin], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RevokedOn], [RevokedBy]) VALUES (N'dedc3b63-cb36-4ad2-ae24-0953f0281acb', N'tiger', N'tiger', N'Tiger', 1, CAST(N'2004-05-30T21:00:30.080' AS DateTime), 0, CAST(N'2024-05-30T21:00:23.507' AS DateTime), N' admin', CAST(N'2024-05-30T21:01:26.973' AS DateTime), N' admin', NULL, NULL)
GO
INSERT [dbo].[Users] ([Guid], [Login], [Password], [Name], [Gender], [Birthday], [Admin], [CreatedOn], [CreatedBy], [ModifiedOn], [ModifiedBy], [RevokedOn], [RevokedBy]) VALUES (N'0122b6cb-b71b-4e82-948c-125f35ea4a2c', N'admin', N'admin', N'Jon', 2, CAST(N'2005-05-30T21:09:30.023' AS DateTime), 1, CAST(N'2024-05-01T11:16:53.917' AS DateTime), N'admin', CAST(N'2024-05-30T21:12:10.277' AS DateTime), N'admin', NULL, NULL)
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Users__5E55825B2A5A6729]    Script Date: 31.05.2024 4:23:42 ******/
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [UQ__Users__5E55825B2A5A6729] UNIQUE NONCLUSTERED 
(
	[Login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_Admin]  DEFAULT ((0)) FOR [Admin]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [CK__Users__Login__4E88ABD4] CHECK  (([Login] like '%[0-9A-Za-z]%'))
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [CK__Users__Login__4E88ABD4]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [CK__Users__Name__5070F446] CHECK  (([Name] like N'%[0-9A-Za-zа-яА-Я]%'))
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [CK__Users__Name__5070F446]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [CK__Users__Password__4F7CD00D] CHECK  (([Password] like '%[0-9A-Za-z]%'))
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [CK__Users__Password__4F7CD00D]
GO
USE [master]
GO
ALTER DATABASE [AtonDB] SET  READ_WRITE 
GO
